# -*- coding: utf-8 -*-
"""WholeClusterRAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SAAJr1CnKyO5fetJIlvchYv16WRA5kLB
"""

!pip install requests pandas srai srai[osm] h3 pytorch_lightning torch contextily google-generativeai --quiet

# Commented out IPython magic to ensure Python compatibility.
# --- 1. System & Standard Library ---
import os
import re
import json
import random
import getpass
import textwrap
import itertools
import warnings
import logging

# --- 2. Warning & Log Suppression ---
# Filter warnings that clutter client output
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore', FutureWarning)
warnings.simplefilter('ignore', UserWarning)
warnings.simplefilter('ignore', DeprecationWarning)
os.environ["PYTHONWARNINGS"] = "ignore"

# Silence verbose library loggers
logging.getLogger("pytorch_lightning").setLevel(logging.ERROR)
logging.getLogger("srai").setLevel(logging.WARNING)

# --- 3. Data Manipulation & Math ---
import numpy as np
import pandas as pd
import geopandas as gpd

# --- 4. Geospatial & H3 ---
import h3
from srai.loaders import OSMPbfLoader
from srai.regionalizers import geocode_to_region_gdf, H3Regionalizer
from srai.joiners import IntersectionJoiner
from srai.embedders import Hex2VecEmbedder
from srai.neighbourhoods import H3Neighbourhood
from srai.loaders.osm_loaders.filters import HEX2VEC_FILTER
from srai.plotting import plot_regions

# --- 5. Machine Learning & Deep Learning ---
import torch
import pytorch_lightning as pl
from pytorch_lightning.callbacks import TQDMProgressBar
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import adjusted_rand_score, silhouette_score

# --- 6. LLM & AI ---
import google.generativeai as genai

# --- 7. Visualization ---
import folium
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

# --- 8. Configuration ---
# Torch matmul precision
torch.set_float32_matmul_precision('medium')

# Pandas display options
pd.set_option('display.max_columns', None)
pd.set_option('mode.chained_assignment', None)

# Matplotlib inline rendering
# %matplotlib inline

print("Libraries loaded. Environment configured for clean output.")

# =====================================================
# 2.1 GLOBAL REPRODUCIBILITY SETUP
# =====================================================
# Setting seeds ensures that the Neural Network (Hex2Vec)
# and other stochastic processes produce the exact same
# results every time you run this notebook.

def set_global_seed(seed=42):
    # 1. Python's built-in random module
    random.seed(seed)

    # 2. NumPy (used for mathematical operations and arrays)
    np.random.seed(seed)

    # 3. PyTorch (used by Hex2Vec for weights initialization)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    # 4. PyTorch Lightning (manages the training loop)
    # This is the most important one for the SRAI library
    pl.seed_everything(seed, workers=True)

# Apply the seed
set_global_seed(42)
print("Global random seed set to 42 for reproducibility.")

area_of_interest = "Blacksburg, VA"
H3_resolution = 10
# 1. Define Region
area = geocode_to_region_gdf(area_of_interest)

# 2. Load OSM Features
loaderpbf = OSMPbfLoader()
loadergdf = loaderpbf.load(area, HEX2VEC_FILTER)

# 3. H3 Regionalization
regionalizer = H3Regionalizer(resolution = H3_resolution)
regions_gdf = regionalizer.transform(loadergdf)

# 4. Join Features to H3 Regions
joiner = IntersectionJoiner()
joint_gdf = joiner.transform(regions_gdf, loadergdf)

# Get the list of feature columns from HEX2VEC_FILTER keys
feature_columns = list(HEX2VEC_FILTER.keys())

# Apply the conversion to 0 or 1 for each feature column
for col in feature_columns:
    loadergdf.loc[:, col] = loadergdf[col].notna().astype(int)

# Get the list of feature columns from HEX2VEC_FILTER keys
feature_columns = list(HEX2VEC_FILTER.keys())
joined_features_df = joint_gdf.reset_index()
merged_df = joined_features_df.merge(
    loadergdf[feature_columns], # Select only the feature columns from loadergdf
    left_on='feature_id',
    right_index=True, # Merge on loadergdf's index ('feature_id')
    how='left'
)

features_per_hex = merged_df.groupby('region_id')[feature_columns].sum()

mod = 'Agglomerative'
res = 10
kring = 1

mod_lower = mod.lower()
html_file_path = f'/content/{mod}_K{kring}_R{res}.html'
cluster_name = f'{mod_lower}_cluster'
html_cluster_data = []
try:
    with open(html_file_path, 'r') as f:
        html_content = f.read()

    json_matches = re.findall(r'geo_json_[a-f0-9]+_add\((\{.*?\})\);', html_content, re.DOTALL)

    if json_matches:
        for json_string in json_matches:
            geo_json_data = json.loads(json_string)

            if 'features' in geo_json_data:
                for feature in geo_json_data['features']:
                    feature_id = None
                    if 'properties' in feature and 'region_id' in feature['properties']:
                        feature_id = feature['properties']['region_id']
                    elif 'id' in feature:
                        feature_id = feature['id']

                    if 'properties' in feature and cluster_name in feature['properties']:
                        html_cluster_data.append({
                            'region_id': feature_id,
                            cluster_name: feature['properties'][cluster_name],
                        })
            else:
                print("Warning: GeoJSON data has no 'features' key in one of the blocks.")
    else:
        print("Could not find GeoJSON data pattern in HTML file.")

except FileNotFoundError:
    print(f"Error: HTML file not found at {html_file_path}")
except json.JSONDecodeError as e:
    print(f"Error decoding JSON from HTML: {e}")
except Exception as e:
    print(f"An unexpected error occurred during HTML processing: {e}")

if html_cluster_data:
    df_html_clusters = pd.DataFrame(html_cluster_data)
    df_html_clusters = df_html_clusters.rename(columns = {cluster_name : 'cluster_id'})
    print(f"Successfully extracted {len(df_html_clusters)} 'hc_cluster' labels and their IDs and geometries from HTML.")
else:
    print("No 'hc_cluster' labels extracted from HTML.")

merged_df = features_per_hex.merge(df_html_clusters, left_index=True, right_on='region_id', how='right')

# ============================================================
# Install dependencies & set API key
# ============================================================

# Prompt once, key never appears as plain text in the notebook
if "GEMINI_API_KEY" not in os.environ:
    os.environ["GEMINI_API_KEY"] = getpass.getpass(
        "Paste your Google AI Studio API key: "
    )

genai.configure(api_key=os.environ["GEMINI_API_KEY"])

# gemini-2.5-flash is free, fast, and well within limits for our purposes
MODEL_NAME = "gemini-2.5-flash"
CLIENT = genai.GenerativeModel(
    model_name=MODEL_NAME,
    system_instruction=textwrap.dedent("""\
        You are an expert urban geographer and GIS analyst.
        You will be given aggregated OpenStreetMap feature statistics for a group
        of H3 hexagonal grid cells that all belong to the same spatial cluster.

        Your task is to write a concise, insightful description of what kind of
        urban area or land-use type this cluster represents. Ground your
        description in the feature statistics provided — mention which features
        dominate, which are absent, and what that implies about the character of
        the area (e.g. commercial district, residential neighbourhood, green
        space, transport hub, mixed-use area, industrial zone, etc.).

        Format your response as:
          1. A one-sentence summary label (e.g. "Dense commercial / retail core").
          2. A paragraph (3–5 sentences) elaborating on the urban character.
          3. A bullet list of the 3–5 most diagnostically important features and
             why each one matters for this cluster type.

        Be specific and avoid generic filler phrases.
    """),
)

print(f"✓ Gemini client ready  (model: {MODEL_NAME})") # AIzaSyAx0BosTIHANbLKHb-PCPRCRciL2w9c4_g

# ============================================================
# Validate & extract feature columns
# ============================================================

RESERVED_COLS = {"region_id", "cluster_id"}

def get_feature_columns(df: pd.DataFrame) -> list[str]:
    """
    Return all numeric columns that are not region_id or cluster_id.
    Raises clearly if required columns are missing.
    """
    missing = RESERVED_COLS - set(df.columns)
    if missing:
        raise ValueError(
            f"DataFrame is missing required column(s): {missing}\n"
            f"Expected columns: region_id, cluster_id, <feature columns...>"
        )

    feature_cols = [c for c in merged_df.columns if c not in {"region_id", "cluster_id"}]
    if not feature_cols:
        raise ValueError("No numeric feature columns found besides region_id / cluster_id.")
    merged_df[feature_cols] = merged_df[feature_cols].astype(float)
    return feature_cols

def list_clusters(df: pd.DataFrame) -> pd.DataFrame:
    """Print a summary table of all clusters in the DataFrame."""
    summary = (
        df.groupby('cluster_id')
          .agg(hex_count=("region_id", "count"))
          .reset_index()
    )
    print("Clusters in DataFrame:")
    print(summary.to_string(index=False))
    return summary

list_clusters(merged_df)

# ============================================================
# Retrieval: aggregate feature statistics per cluster
# ============================================================

def aggregate_cluster_stats(
    df: pd.DataFrame,
    cluster_id: int,
    top_n: int = 10,
) -> tuple[pd.DataFrame, list[str], list[str]]:
    """
    Filter to the chosen cluster and compute per-feature stats:
      mean, max, presence_rate (fraction of hexes where feature > 0).

    Returns
    -------
    stats_df   : DataFrame with one row per feature, sorted by salience.
    top_feats  : feature names in the top_n by salience.
    absent     : feature names with presence_rate < 5%.
    """
    feature_cols = get_feature_columns(df)
    cluster_df = df[df["cluster_id"] == cluster_id]

    if cluster_df.empty:
        available = sorted(df["cluster_id"].unique().tolist())
        raise ValueError(
            f"Cluster ID {cluster_id} not found.\n"
            f"Available cluster IDs: {available}"
        )

    records = []
    for col in feature_cols:
        vals          = cluster_df[col].astype(float)
        mean_val      = float(vals.mean())
        max_val       = float(vals.max())
        presence_rate = float((vals > 0).mean())
        salience      = presence_rate * mean_val
        records.append({
            "feature":       col,
            "mean":          round(mean_val, 2),
            "max":           int(max_val),
            "presence_rate": round(presence_rate, 2),
            "salience":      round(salience, 4),
        })

    stats_df = (
        pd.DataFrame(records)
          .sort_values("salience", ascending=False)
          .reset_index(drop=True)
    )

    top_feats = stats_df.head(top_n)["feature"].tolist()
    absent    = stats_df[stats_df["presence_rate"] < 0.05]["feature"].tolist()

    return stats_df, top_feats, absent


# ============================================================
# Augmentation: building the context block
# ============================================================

def build_context_block(
    df: pd.DataFrame,
    cluster_id: int,
    stats_df: pd.DataFrame,
    top_feats: list[str],
    absent: list[str],
    top_n: int = 10,
) -> str:
    """
    Format retrieved statistics into a structured text block
    that will be injected into the LLM prompt.
    """
    cluster_df = df[df["cluster_id"] == cluster_id]
    hex_ids    = cluster_df["region_id"].tolist()
    top_stats  = stats_df[stats_df["feature"].isin(top_feats)].head(top_n)

    lines = [
        f"Cluster ID      : {cluster_id}",
        f"Hex count       : {len(cluster_df)}",
        f"Hex IDs         : {', '.join(hex_ids)}",
        "",
        f"Top {top_n} features by salience  (presence_rate × mean count):",
        f"  {'Feature':<24} {'Mean':>6}  {'Max':>5}  {'Presence':>9}",
        f"  {'-'*24} {'-'*6}  {'-'*5}  {'-'*9}",
    ]
    for _, row in top_stats.iterrows():
        lines.append(
            f"  {row['feature']:<24} {row['mean']:>6.2f}  "
            f"{row['max']:>5}  {row['presence_rate']*100:>8.0f}%"
        )

    if absent:
        lines += ["", f"Absent / rare features (<5% presence): {', '.join(absent)}"]

    return "\n".join(lines)


# ============================================================
# Generation: calling the Gemini API
# ============================================================

def describe_cluster(context_block: str, cluster_id: int) -> str:
    """Send the context block to Gemini and return the description."""
    prompt = (
        f"Please describe Cluster {cluster_id} based on the following "
        f"aggregated feature statistics retrieved from its member hexagons:\n\n"
        f"{context_block}"
    )
    response = CLIENT.generate_content(prompt)
    return response.text

# ============================================================
# Full RAG pipeline
# ============================================================

def run_rag_pipeline(
    df: pd.DataFrame,
    cluster_id: int,
    top_n: int = 10,
    verbose: bool = True,
) -> str:
    """
    End-to-end RAG pipeline.

    Parameters
    ----------
    df          : merged DataFrame with region_id, cluster_id, feature cols.
    cluster_id  : which cluster to describe.
    top_n       : number of top features to include in the context.
    verbose     : if True, print the context block before calling the API.

    Returns
    -------
    description : natural-language cluster description from Gemini.
    """
    # --- Retrieve ---
    stats_df, top_feats, absent = aggregate_cluster_stats(df, cluster_id, top_n)

    # --- Augment ---
    context_block = build_context_block(df, cluster_id, stats_df, top_feats, absent, top_n)

    if verbose:
        print("── Retrieved context block " + "─" * 34)
        #print(textwrap.fill(context_block, width=100))
        print(context_block)
        print("─" * 60 + "\n")

    # --- Generate ---
    print(f"Calling API for Cluster {cluster_id}…")
    description = describe_cluster(context_block, cluster_id)
    return description #AIzaSyAx0BosTIHANbLKHb-PCPRCRciL2w9c4_g

# ============================================================
# Change cluster_id to whichever you want
# ============================================================
TARGET_CLUSTER = 1   # ← change this
description = run_rag_pipeline(merged_df, cluster_id=TARGET_CLUSTER)
print(f"\n{'='*60}")
print(f"  Cluster {TARGET_CLUSTER} — Description")
print(f"{'='*60}")
wrapped = "\n\n".join(textwrap.fill(p, width=100) for p in description.split("\n\n"))
print(wrapped)
print("=" * 60)
